### ISSUE TITLE
Installing open_gem causes warning: "loading in progress, circular require considered harmful" in Ruby 1.9.2

### ISSUE THREAD

**Issue by weppos** [adamsanderson/open_gem#9]
With `open_gem` installed

```
$ ruby-whois google.su
<internal:lib/rubygems/custom_require>:29: warning: loading in progress, circular require considered harmful - /Users/weppos/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems.rb
    from /Users/weppos/.rvm/gems/ruby-1.9.2-p0/bin/ruby-whois:9:in `<main>'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /Users/weppos/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems.rb:1136:in `<top (required)>'
    from /Users/weppos/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems.rb:968:in `load_plugins'
    from /Users/weppos/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems.rb:968:in `each'
    from /Users/weppos/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems.rb:976:in `block in load_plugins'
    from /Users/weppos/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems.rb:976:in `load'
    from /Users/weppos/.rvm/gems/ruby-1.9.2-p0/gems/open_gem-1.4.2/lib/rubygems_plugin.rb:5:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from /Users/weppos/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems/version_option.rb:7:in `<top (required)>'
    from <internal:lib/rubygems/custom_require>:29:in `require'
    from <internal:lib/rubygems/custom_require>:29:in `require'
c
^C/Users/weppos/.rvm/gems/ruby-1.9.2-p0/gems/whois-1.6.6/lib/whois/server/adapters/base.rb:126:in `initialize': Interrupt
    from /Users/weppos/.rvm/gems/ruby-1.9.2-p0/gems/whois-1.6.6/lib/whois/server/adapters/base.rb:126:in `open'
    from /Users/weppos/.rvm/gems/ruby-1.9.2-p0/gems/whois-1.6.6/lib/whois/server/adapters/base.rb:126:in `ask_the_socket'
    from /Users/weppos/.rvm/gems/ruby-1.9.2-p0/gems/whois-1.6.6/lib/whois/server/adapters/base.rb:120:in `query_the_socket'
    from /Users/weppos/.rvm/gems/ruby-1.9.2-p0/gems/whois-1.6.6/lib/whois/server/adapters/standard.rb:34:in `request'
    from /Users/weppos/.rvm/gems/ruby-1.9.2-p0/gems/whois-1.6.6/lib/whois/server/adapters/base.rb:85:in `block in query'
    from /Users/weppos/.rvm/gems/ruby-1.9.2-p0/gems/whois-1.6.6/lib/whois/server/adapters/base.rb:109:in `with_buffer'
    from /Users/weppos/.rvm/gems/ruby-1.9.2-p0/gems/whois-1.6.6/lib/whois/server/adapters/base.rb:84:in `query'
    from /Users/weppos/.rvm/gems/ruby-1.9.2-p0/gems/whois-1.6.6/lib/whois/client.rb:79:in `block in query'
    from /Users/weppos/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/timeout.rb:57:in `timeout'
    from /Users/weppos/.rvm/gems/ruby-1.9.2-p0/gems/whois-1.6.6/lib/whois/client.rb:77:in `query'
    from /Users/weppos/.rvm/gems/ruby-1.9.2-p0/gems/whois-1.6.6/bin/ruby-whois:52:in `<top (required)>'
    from /Users/weppos/.rvm/gems/ruby-1.9.2-p0/bin/ruby-whois:19:in `load'
    from /Users/weppos/.rvm/gems/ruby-1.9.2-p0/bin/ruby-whois:19:in `<main>'
```

Without `open_gem`

```
$ gem uninstall open_gem
Successfully uninstalled open_gem-1.4.2
weppos-macair:whois weppos$ ruby-whois google.su
...
```

The library I'm using is the [whois gem](http://www.ruby-whois.org/).

**Comment by adamsanderson** [comment]
Does this happen with all gems you try to load or just ruby-whois?  

This looks a little odd `/Users/weppos/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems.rb`, you have ruby 1.9.2 installed, but then have `ruby/1.9.1 rubygems`, I couldn't say if that was a problem though.

In general, I'm not really supporting open_gem anymore, I would suggest trying out [qwandry](https://github.com/adamsanderson/qwandry).

**Comment by weppos** [comment]
The reason why the path includes 1.9.1 is because Ruby core decide to not change the rubygems path.

So far, it just happens with this Gem, but I didn't have the time to run additional tests.
